title: "Documentation Example Using Just the Docs"
remote_theme: pmarsceill/just-the-docs
color_scheme: "nil"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/
